// <auto-generated />
namespace SupplyFlow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddActionTypeToPOAction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddActionTypeToPOAction));
        
        string IMigrationMetadata.Id
        {
            get { return "202505221232530_AddActionTypeToPOAction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
